name: C/C++ CI

on:
  push:
    branches: [ next-opengl3 ]
  pull_request:
    branches: [ next-opengl3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: NX-Shell.nro
        path: NX-Shell.nro
